### ISSUE TITLE
Repository chrome-gnome-shell migrated to GNOME infrastructure

### ISSUE THREAD

**Issue by nE0sIghT** [winsock/gs-chrome-connector-aur#1]
Hi,

I just imported [chrome-gnome-shell repository](https://github.com/nE0sIghT/chrome-gnome-shell) to [git.gnome.org](https://git.gnome.org/browse/chrome-gnome-shell/), so it's a time to change links in your package.

All GNOME repositories are [mirrored at github ](https://github.com/GNOME) so it will be good choice to use github mirror: https://github.com/GNOME/chrome-gnome-shell

Also [with that change](https://github.com/GNOME/chrome-gnome-shell/commit/a4426cea24be1a8d764705a275b16a39fecc70e6) extension now installed automatically at next browser start so package now provides complete solution not just connector. It may be a good idea to rename package to chrome-gnome-shell (it is an easy move in Gentoo with preserving all user metadata however I'm in doubt about Arch).

**Comment by winsock** [comment]
@nE0sIghT Done, you have to make a new package but the metadata can be merged in the AUR I just submitted a request to do so. you will need to update the link for me though:
https://aur.archlinux.org/packages/chrome-gnome-shell-git/

**Comment by nE0sIghT** [comment]
Source and Chrome Store done
